name: "Henri Bergius"
url: "http://bergie.iki.fi"
author: "henri.bergius@iki.fi (Henri Bergius)"
author_name: "Henri Bergius"
author_url: "http://bergie.iki.fi/about"
icon: 'http://bergie.iki.fi/style/img/mdpi/bergie.jpg'
language: "en"
permalink: /blog/:title/
paginate: 10
highlighter: null
collections:
  now:
    output: false
gems:
- jekyll-paginate
