name: Publish on AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true
    - run: sudo apt-get install -y bundler
    - run: bundle install --path vendor/bundle
    - run: bundle exec jekyll build -V
    - name: Deploy on S3
      uses: reggionick/s3-deploy@v3
      with:
        folder: _site
        bucket: bergie.iki.fi
        bucket-region: eu-central-1
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        private: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Update search engines
      uses: atymic/sitemap-ping-action@master
      with:
        sitemap-url: 'https://bergie.iki.fi/sitemap.xml'
