name: CI

on: [push, pull_request]

jobs:
  test:
    name: Build the site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: sudo apt-get install -y bundler
    - run: bundle install --path vendor/bundle
    - run: bundle exec jekyll build -V
      env:
        CI: true
  merge-me:
    name: Auto-merge dependency updates
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: ridedott/merge-me-action@v2.9.145
      with:
        GITHUB_LOGIN: 'dependabot[bot]'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
